version: '3.8'

services:
  db-proyekku:
    image: postgres:15-alpine
    container_name: postgres_flutter
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rezza
      POSTGRES_PASSWORD: rahasia_kora
      POSTGRES_DB: db_proyekku
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
