name: kora
description: "Kora - Personal Digital Assistant for Athletes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.10.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  flutter_foreground_task: ^8.0.0
  path_provider: ^2.1.5
  google_sign_in: ^6.2.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  http: ^1.6.0
  flutter_web_auth_2: ^5.0.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.4
  audioplayers: ^6.6.0
  vibration: ^3.1.8
  wakelock_plus: ^1.5.2
  liquid_progress_indicator_v2: ^0.5.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  quick_actions: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#093247"
  adaptive_icon_foreground: "assets/icons/logo.png"
