import 'package:flutter/material.dart';

class ExerciseDefinition {
  final String id;
  final String name;
  final String category; // 'bodyweight' | 'weighted'
  final List<String> muscleGroups; 
  final String techniqueTip;
  final IconData icon;
  final String difficulty; 
  final String? gifPath;

  const ExerciseDefinition({
    required this.id,
    required this.name,
    required this.category,
    required this.muscleGroups,
    required this.techniqueTip,
    required this.icon,
    this.difficulty = 'Beginner',
    this.gifPath,
  });
}

// Master List of Exercises (Katalog Latihan)
final List<ExerciseDefinition> exerciseDatabase = [
  // ==========================================
  // KATEGORI: BODYWEIGHT
  // ==========================================
  
  // -- Chest & Triceps --
  const ExerciseDefinition(
    id: 'bw_pushup',
    name: 'Standard Push-up',
    category: 'bodyweight',
    muscleGroups: ['Dada', 'Tricep', 'Bahu Depan'],
    techniqueTip: 'Jaga tubuh tetap lurus dari kepala hingga tumit dan kunci bagian core.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/standar_push_up.gif',
  ),
  const ExerciseDefinition(
    id: 'bw_wide_pushup',
    name: 'Wide Push-up',
    category: 'bodyweight',
    muscleGroups: ['Dada', 'Bahu Depan'],
    techniqueTip: 'Posisikan tangan lebih lebar dari bahu untuk tekanan ekstra pada dada samping.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/wide_push_up.gif',
  ),
  const ExerciseDefinition(
    id: 'bw_diamond_pushup',
    name: 'Diamond Push-up',
    category: 'bodyweight',
    muscleGroups: ['Tricep', 'Dada'],
    techniqueTip: 'Pastikan siku tetap rapat ke arah badan saat menekuk. Dekatkan tangan membentuk berlian.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/diamond_push_up.gif',
  ),
  const ExerciseDefinition(
    id: 'bw_decline_pushup',
    name: 'Decline Push-up',
    category: 'bodyweight',
    muscleGroups: ['Dada', 'Bahu Depan'],
    techniqueTip: 'Posisikan kaki lebih tinggi dari kepala, fokus pada dada bagian atas.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/decline_push_up.gif',
  ),
  const ExerciseDefinition(
    id: 'bw_bench_dips',
    name: 'Bench Dips',
    category: 'bodyweight',
    muscleGroups: ['Tricep', 'Dada'],
    techniqueTip: 'Turunkan pinggul mendekati kursi, gunakan otot tricep untuk mendorong tubuh naik.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/bench_dips.gif',
  ),

  // -- Back & Biceps --
  const ExerciseDefinition(
    id: 'bw_pullup',
    name: 'Pull-up',
    category: 'bodyweight',
    muscleGroups: ['Punggung Samping', 'Bicep'],
    techniqueTip: 'Tarik bahu ke bawah dan pastikan dagu melewati palang saat naik.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'bw_wide_pullup',
    name: 'Wide Grip Pull-up',
    category: 'bodyweight',
    muscleGroups: ['Punggung Samping'],
    techniqueTip: 'Bayangkan menarik siku ke arah pinggul untuk mengaktifkan sayap punggung.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Advanced',
  ),
  const ExerciseDefinition(
    id: 'bw_chinup',
    name: 'Chin-up',
    category: 'bodyweight',
    muscleGroups: ['Bicep', 'Punggung Samping'],
    techniqueTip: 'Fokus pada kontraksi otot lengan depan, pastikan siku mengarah ke bawah.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/chin_up.gif',
  ),
  const ExerciseDefinition(
    id: 'bw_inverted_row',
    name: 'Inverted Row',
    category: 'bodyweight',
    muscleGroups: ['Punggung Samping', 'Bicep'],
    techniqueTip: 'Gunakan meja atau tiang rendah, tarik dada ke arah pegangan.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/inverted__row.gif',
  ),
  const ExerciseDefinition(
    id: 'bw_superman',
    name: 'Superman',
    category: 'bodyweight',
    muscleGroups: ['Punggung Bawah', 'Pantat'],
    techniqueTip: 'Angkat dada dan paha dari lantai secara bersamaan, tahan sejenak di puncak.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),

  // -- Shoulders & Forearms --
  const ExerciseDefinition(
    id: 'bw_pike_pushup',
    name: 'Pike Push-up',
    category: 'bodyweight',
    muscleGroups: ['Bahu Depan', 'Tricep'],
    techniqueTip: 'Jaga punggung tetap tegak, jangan biarkan tubuh condong ke belakang. Pinggul tinggi.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'bw_hspu',
    name: 'Handstand Push-up',
    category: 'bodyweight',
    muscleGroups: ['Bahu Depan', 'Tricep'],
    techniqueTip: 'Gunakan dinding untuk keseimbangan, turun perlahan hingga kepala menyentuh lantai.',
    icon: Icons.sports_gymnastics_rounded,
    difficulty: 'Advanced',
  ),
  const ExerciseDefinition(
    id: 'bw_dead_hang',
    name: 'Dead Hang',
    category: 'bodyweight',
    muscleGroups: ['Forearm', 'Punggung Samping'],
    techniqueTip: 'Genggam palang dengan kuat untuk melatih kekuatan cengkeraman, biarkan tubuh menggantung bebas.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),

  // -- Legs --
  const ExerciseDefinition(
    id: 'bw_air_squat',
    name: 'Air Squat',
    category: 'bodyweight',
    muscleGroups: ['Paha Depan', 'Pantat'],
    techniqueTip: 'Turunkan pinggul seperti hendak duduk dan pastikan tumit tetap menempel di lantai.',
    icon: Icons.directions_run_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'bw_lunges',
    name: 'Lunges',
    category: 'bodyweight',
    muscleGroups: ['Paha Depan', 'Pantat'],
    techniqueTip: 'Langkah ke depan, turunkan pinggul hingga kedua lutut membentuk sudut 90 derajat.',
    icon: Icons.directions_walk_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/bb_lunges.gif',
  ),
  const ExerciseDefinition(
    id: 'bw_lateral_lunges',
    name: 'Lateral Lunges',
    category: 'bodyweight',
    muscleGroups: ['Paha Samping', 'Paha Depan', 'Pantat'],
    techniqueTip: 'Melangkah ke samping secara lebar dan jaga posisi kaki yang lain tetap lurus.',
    icon: Icons.directions_walk_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'bw_sumo_squat',
    name: 'Sumo Squat',
    category: 'bodyweight',
    muscleGroups: ['Paha Dalam', 'Paha Depan', 'Pantat'],
    techniqueTip: 'Buka kaki lebih lebar dan arahkan lutut ke luar saat posisi turun.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'bw_bulgarian_split',
    name: 'Bulgarian Split Squat',
    category: 'bodyweight',
    muscleGroups: ['Paha Depan', 'Pantat'],
    techniqueTip: 'Jaga keseimbangan dan pastikan lutut depan tidak melewati ujung jari kaki.',
    icon: Icons.sports_gymnastics_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'bw_nordic_curls',
    name: 'Nordic Curls',
    category: 'bodyweight',
    muscleGroups: ['Paha Belakang'],
    techniqueTip: 'Turunkan tubuh bagian atas secara perlahan dengan lutut sebagai tumpuan, tahan tarikan di paha belakang.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Advanced',
  ),
  const ExerciseDefinition(
    id: 'bw_calf_raise',
    name: 'Calf Raise',
    category: 'bodyweight',
    muscleGroups: ['Betis'],
    techniqueTip: 'Angkat tumit setinggi mungkin dan tahan satu detik di posisi jinjit.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'bw_glute_bridge',
    name: 'Glute Bridge',
    category: 'bodyweight',
    muscleGroups: ['Pantat', 'Punggung Bawah'],
    techniqueTip: 'Tekan tumit ke lantai dan remas otot pantat di posisi puncak.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'bw_fire_hydrants',
    name: 'Fire Hydrants',
    category: 'bodyweight',
    muscleGroups: ['Paha Samping', 'Pantat'],
    techniqueTip: 'Buka kaki ke samping dalam posisi merangkak, fokus pada kontraksi paha luar.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'bw_side_lying_adduction',
    name: 'Side Lying Adduction',
    category: 'bodyweight',
    muscleGroups: ['Paha Dalam'],
    techniqueTip: 'Berbaring miring, angkat kaki bagian bawah lurus ke atas ke arah langit-langit.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),

  // -- Core --
  const ExerciseDefinition(
    id: 'bw_plank',
    name: 'Plank',
    category: 'bodyweight',
    muscleGroups: ['Perut Depan'],
    techniqueTip: 'Tahan posisi tubuh tetap sejajar, jangan biarkan pinggul merosot atau terlalu naik.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'bw_crunch',
    name: 'Crunch',
    category: 'bodyweight',
    muscleGroups: ['Perut Depan'],
    techniqueTip: 'Tekan punggung bawah ke lantai saat mengangkat bahu, rasakan kontraksi perut.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'bw_leg_raise',
    name: 'Leg Raise',
    category: 'bodyweight',
    muscleGroups: ['Perut Depan'],
    techniqueTip: 'Tekan punggung bawah ke lantai saat mengangkat kaki.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'bw_russian_twist',
    name: 'Russian Twist',
    category: 'bodyweight',
    muscleGroups: ['Perut Samping'],
    techniqueTip: 'Putar batang tubuh secara perlahan untuk melatih sisi samping perut.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'bw_side_plank',
    name: 'Side Plank',
    category: 'bodyweight',
    muscleGroups: ['Perut Samping'],
    techniqueTip: 'Angkat pinggul dari lantai dan tahan tubuh dalam garis lurus menyamping.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
  ),

  // ==========================================
  // KATEGORI: WEIGHTED
  // ==========================================

  // -- Chest & Triceps --
  const ExerciseDefinition(
    id: 'wt_flat_bench',
    name: 'Flat Bench Press',
    category: 'weighted',
    muscleGroups: ['Dada', 'Tricep', 'Bahu Depan'],
    techniqueTip: 'Turunkan bar perlahan ke arah tengah dada dan pastikan siku tidak terlalu melebar.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'wt_incline_bench',
    name: 'Incline Bench Press',
    category: 'weighted',
    muscleGroups: ['Dada Atas', 'Tricep', 'Bahu Depan'],
    techniqueTip: 'Gunakan kemiringan bangku 30-45 derajat untuk memfokuskan tarikan pada otot dada bagian atas.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/incline_bench_press.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_tricep_pushdown',
    name: 'Tricep Pushdown',
    category: 'weighted',
    muscleGroups: ['Tricep'],
    techniqueTip: 'Jaga siku agar tetap menempel pada sisi tubuh dan dorong kabel lurus ke bawah.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/triceps_pulldown.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_db_flyes',
    name: 'Dumbbell Flyes',
    category: 'weighted',
    muscleGroups: ['Dada'],
    techniqueTip: 'Buka lengan ke samping dengan sedikit tekukan di siku, rasakan tarikan di dada.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/dumbell_flys.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_skull_crushers',
    name: 'Skull Crushers',
    category: 'weighted',
    muscleGroups: ['Tricep'],
    techniqueTip: 'Pastikan siku tetap rapat ke arah badan saat menekuk. Turunkan beban ke arah dahi.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/skull_crushers.gif',
  ),

  // -- Back & Biceps --
  const ExerciseDefinition(
    id: 'wt_barbell_row',
    name: 'Barbell Row',
    category: 'weighted',
    muscleGroups: ['Punggung Samping', 'Bicep'],
    techniqueTip: 'Tarik beban ke arah pusar sambil menjaga punggung tetap lurus dan sejajar lantai.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'wt_lat_pulldown',
    name: 'Lat Pulldown',
    category: 'weighted',
    muscleGroups: ['Punggung Samping', 'Bicep'],
    techniqueTip: 'Bayangkan menarik siku ke arah pinggul untuk mengaktifkan sayap punggung.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/lat_pulldown.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_seated_row',
    name: 'Seated Cable Row',
    category: 'weighted',
    muscleGroups: ['Punggung Tengah', 'Bicep'],
    techniqueTip: 'Jaga dada tetap tegak dan tarik handle ke arah perut bawah sambil merapatkan tulang belikat.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/seated_row.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_deadlift',
    name: 'Deadlift',
    category: 'weighted',
    muscleGroups: ['Punggung Bawah', 'Paha Belakang', 'Pantat'],
    techniqueTip: 'Dorong lantai dengan kaki dan pastikan punggung tidak melengkung saat mengangkat.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Advanced',
    gifPath: 'assets/exercises/deadlift.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_shrugs',
    name: 'Barbell Shrugs',
    category: 'weighted',
    muscleGroups: ['Punggung Atas'],
    techniqueTip: 'Angkat bahu mendekati telinga tanpa menekuk siku tangan.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/shrugs.gif',
  ),

  const ExerciseDefinition(
    id: 'wt_db_curl',
    name: 'Dumbbell Bicep Curl',
    category: 'weighted',
    muscleGroups: ['Bicep'],
    techniqueTip: 'Fokus pada kontraksi otot lengan depan, jangan ayunkan beban.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/db_curl.gif',
  ),

  // -- Shoulders & Forearms --
  const ExerciseDefinition(
    id: 'wt_overhead_press',
    name: 'Overhead Press',
    category: 'weighted',
    muscleGroups: ['Bahu Depan', 'Tricep'],
    techniqueTip: 'Dorong beban lurus ke atas kepala tanpa mengayunkan badan atau menekuk lutut.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/overhead_press.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_front_raise',
    name: 'Front Raise',
    category: 'weighted',
    muscleGroups: ['Bahu Depan'],
    techniqueTip: 'Jaga punggung tetap tegak, jangan biarkan tubuh condong ke belakang saat mengangkat.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/front_raise.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_lateral_raise',
    name: 'Lateral Raise',
    category: 'weighted',
    muscleGroups: ['Bahu Samping'],
    techniqueTip: 'Angkat beban ke samping hingga setinggi bahu dengan siku sedikit ditekuk.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/lateral_raise.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_face_pull',
    name: 'Face Pull',
    category: 'weighted',
    muscleGroups: ['Bahu Belakang', 'Punggung Atas'],
    techniqueTip: 'Tarik beban ke arah wajah sambil merapatkan tulang belikat.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'wt_reverse_flyes',
    name: 'Reverse Flyes',
    category: 'weighted',
    muscleGroups: ['Bahu Belakang'],
    techniqueTip: 'Bungkukkan tubuh dan rentangkan tangan ke samping, tarik tulang belikat.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'wt_wrist_curl',
    name: 'Wrist Curl',
    category: 'weighted',
    muscleGroups: ['Forearm'],
    techniqueTip: 'Genggam alat dengan kuat, gulung pergelangan tangan ke atas untuk memeras lengan bawah.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/wrist_curl.gif',
  ),

  // -- Legs --
  const ExerciseDefinition(
    id: 'wt_barbell_squat',
    name: 'Barbell Back Squat',
    category: 'weighted',
    muscleGroups: ['Paha Depan', 'Pantat', 'Paha Belakang'],
    techniqueTip: 'Jaga punggung lurus, turun perlahan hingga paha sejajar dengan lutut atau lebih rendah.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'wt_goblet_squat',
    name: 'Goblet Squat',
    category: 'weighted',
    muscleGroups: ['Paha Depan', 'Pantat'],
    techniqueTip: 'Dorong beban menggunakan kekuatan paha hingga kaki lurus sempurna.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/goblet_squat.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_leg_extension',
    name: 'Leg Extension',
    category: 'weighted',
    muscleGroups: ['Paha Depan'],
    techniqueTip: 'Dorong beban menggunakan kekuatan paha depan hingga kaki lurus sempurna.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
    gifPath: 'assets/exercises/leg_extension.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_leg_curl',
    name: 'Lying/Seated Leg Curl',
    category: 'weighted',
    muscleGroups: ['Paha Belakang'],
    techniqueTip: 'Tarik beban menggunakan paha belakang hingga tumit mendekati bokong.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Beginner',
  ),
  const ExerciseDefinition(
    id: 'wt_rdl',
    name: 'Romanian Deadlift',
    category: 'weighted',
    muscleGroups: ['Paha Belakang', 'Pantat', 'Punggung Bawah'],
    techniqueTip: 'Tekuk pinggul ke belakang sampai terasa tarikan maksimal di paha belakang.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/rdl.gif',
  ),
  const ExerciseDefinition(
    id: 'wt_hip_thrust',
    name: 'Barbell Hip Thrust',
    category: 'weighted',
    muscleGroups: ['Pantat'],
    techniqueTip: 'Tekan tumit ke lantai dan remas otot pantat di posisi puncak dorongan.',
    icon: Icons.fitness_center_rounded,
    difficulty: 'Intermediate',
  ),
  const ExerciseDefinition(
    id: 'wt_bb_lunges',
    name: 'Barbell Lunges',
    category: 'weighted',
    muscleGroups: ['Paha Depan', 'Pantat'],
    techniqueTip: 'Jaga torso tetap tegak dan melangkah cukup jauh agar lutut membentuk sudut 90 derajat.',
    icon: Icons.directions_walk_rounded,
    difficulty: 'Intermediate',
    gifPath: 'assets/exercises/bb_lunges.gif',
  ),

  // -- Core --
  const ExerciseDefinition(
    id: 'wt_weighted_plank',
    name: 'Weighted Plank',
    category: 'weighted',
    muscleGroups: ['Perut Depan'],
    techniqueTip: 'Letakkan piringan beban di punggung bawah dan tahan posisi plank.',
    icon: Icons.accessibility_new_rounded,
    difficulty: 'Advanced',
  ),
];
